/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.screen;

import Interface.InsertValue;
import Interface.CreatingType;
import Modelo.Terminal;
import java.util.ArrayList;
import java.util.List;
import java.util.Observer;

/**
 *
 * @author victor
 */
public class InsertValueFrame extends javax.swing.JFrame {
    
    
    /**
     * Creates new form InsertValue
     */
    public InsertValueFrame() {
        initComponents();
    }
    
        /**
     * Creates new form InsertValue
     */
    public InsertValueFrame(String customText) {
        
        initComponents();
        customTextLabel.setText(customText);
        
    }
    
        /**
     * Creates new form InsertValue
     */
    public InsertValueFrame(String customText1, String customText2) {
        
        initComponents();
        this.customText = customText1;
        customTextLabel.setText(customText);
        this.customText2 = customText2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        textArea = new javax.swing.JTextField();
        customTextLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Inserir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textArea.setToolTipText("Valor do Nodo");
        textArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAreaActionPerformed(evt);
            }
        });

        customTextLabel.setText("Insira o valor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customTextLabel)
                            .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(customTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(insertValue.getCreatingType() == CreatingType.NodesDijkstra || insertValue.getCreatingType() == CreatingType.NodesCriticalPath){
            
            if(insertValue.getV1().isEmpty()){
                
                insertValue.setV1Algorithm(this.textArea.getText());
                customTextLabel.setText(customText2);
                clearText();
                textArea.requestFocus();
                
                
            }
            else{
                
                insertValue.setV2Algorithm(this.textArea.getText());          
                customTextLabel.setText(DEFAULT_TEXT);  
                clearText();
                textArea.requestFocus();
                setVisible(false);
                
            }
            
        }else{
        
            insertValue.setValue(this.textArea.getText());

            if(insertValue.getValue().isEmpty()){

                return;

            }
            if(insertValue.getCreatingType() == CreatingType.Edge && !insertValue.getValue().matches("[0-9]+")){

                return;

            }

            clearText();
            customTextLabel.setText(DEFAULT_TEXT);
            textArea.requestFocus();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
   
    public String getValue(){
        
        return insertValue.getValue();
        
    }
    
    public void addObserver(Observer obs){
        
        insertValue.addObserver(obs);
        
    }
    
    private void textAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAreaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customTextLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField textArea;
    // End of variables declaration//GEN-END:variables
    InsertValue insertValue = new InsertValue();
    private String customText;
    private String customText2;
    private final String DEFAULT_TEXT = "Insira o valor";
    
    public void setCreatingType(CreatingType creatingType) {

        insertValue.setCreatingType(creatingType);

    }
    
    public void clearText(){
        
        textArea.setText("");
        
    }
    
    public void focusTextArea(){
        
        textArea.requestFocus();
        
    }
    
    public void setCustomText(String text){
        
        customTextLabel.setText(text);
        
    }
    
    public CreatingType getCreatingType() {
        
        return insertValue.getCreatingType();
    
    }

    
}

