/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.screen;

import Modelo.Terminal;
import java.awt.Color;
import java.util.Observable;
import javax.swing.JTextArea;
import java.util.Observer;

/**
 *
 * @author victor
 */
public class TerminalPanel extends javax.swing.JPanel implements Observer {

   
    /**
     * Creates new form TerminalPanel
     */
    public TerminalPanel(JTextArea aTerminal) {
        
        this.terminalTextArea = aTerminal;
        terminal = Terminal.getTerminal();
        terminal.addObserver(this);
        terminalTextArea.setText(terminal.getText());
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        terminalTextArea = terminalTextArea;

        terminalTextArea.setEditable(false);
        terminalTextArea.setColumns(20);
        terminalTextArea.setRows(5);
        jScrollPane1.setViewportView(terminalTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void update(Observable o, Object arg) {
        
        terminalTextArea.setText(terminal.getText());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea terminalTextArea;
    // End of variables declaration//GEN-END:variables
    private Terminal terminal;
        
}
